In [ ]:
#imports
from sklearn.metrics import recall_score, r2_score, precision_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.linear_model import LogisticRegressionCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split
import pandas as pd
import numpy as np


In [ ]:
model = RandomForestClassifier()
params = {'max_depth': (1, 20, 30),
          'min_samples_leaf': (3, 4)}
grid = GridSearchCV(estimator=model,
                    param_grid=params)
grid.fit()

TypeError: BaseSearchCV.fit() missing 1 required positional argument: 'X'

In [6]:
l1 = [1,2,3]
l2 = [2,4,6]
d = {'mon':l1, 'tue':l2}
res = d.values()
l1.append(4)
d['tue'].append(8)
print(res)

dict_values([[1, 2, 3, 4], [2, 4, 6, 8]])


In [7]:
import numpy as np 
x = np.array([
[2, 4, 6, 8],
[3, 6, 9, 12],
[4, 8, 12, 16]
])

a = x[1:, ::-1]
b = x[[False, True, True], :0:-1]
print(a)
print(b)

[[12  9  6  3]
 [16 12  8  4]]
[[12  9  6]
 [16 12  8]]


In [8]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer, MinMaxScaler 
from sklearn.pipeline import make_pipeline

pipe1 = make_pipeline(
    MinMaxScaler()
    )

pipe2 = make_pipeline(
    MinMaxScaler(),
    FunctionTransformer(lambda x: 1 / (x**2+1))
)
X = np.array([
    [1,2],
    [3,5],
    [2,10],
])
print (pipe1.fit_transform(X))
print (pipe2.fit_transform(X))

[[0.    0.   ]
 [1.    0.375]
 [0.5   1.   ]]
[[1.         1.        ]
 [0.5        0.87671233]
 [0.8        0.5       ]]


In [9]:
import pandas as pd

pd.DataFrame()

""


In [12]:
from bs4 import BeautifulSoup, Comment
import re

def clean_html_professional(html_content):
    if not isinstance(html_content, str):
        return ""

    soup = BeautifulSoup(html_content, "html.parser")

    # 1. SALVARE I METADATA PREZIOSI (Opzionale, ma consigliato)
    meta_desc = ""
    meta_tag = soup.find('meta', attrs={'name': 'description'})
    if meta_tag and 'content' in meta_tag.attrs:
        meta_desc = meta_tag['content']

    # 2. GESTIONE JSON-LD (Dati strutturati)
    # Se vuoi estrarre info specifiche da qui, fallo ora prima di rimuovere gli script.

    # 3. RIMOZIONE DEL RUMORE (Decompose distrugge il tag e il suo contenuto)
    for tag in soup(['script', 'style', 'noscript', 'iframe', 'svg', 'header', 'footer', 'nav']):
        # Eccezione: se vuoi tenere JSON-LD, controlla l'attributo type prima di decomporre script
        tag.decompose()

    # Rimuovi commenti HTML
    comments = soup.find_all(string=lambda text: isinstance(text, Comment))
    for c in comments:
        c.extract()

    # 4. ESTRAZIONE ATTRIBUTI NASCOSTI (Come chiedevi per le immagini)
    # Sostituiamo l'immagine con il suo testo alternativo per non perderlo
    for img in soup.find_all('img'):
        if 'alt' in img.attrs and img['alt']:
            # Sostituisce <img> con il testo dell'alt
            img.replace_with(f" {img['alt']} ") 
    
    # 5. ESTRAZIONE TESTO (Gestione spaziature)
    # 'separator=" "' è CRUCIALE. Altrimenti <p>Hello</p><p>World</p> diventa "HelloWorld"
    text = soup.get_text(separator=' ', strip=True)
    
    # Aggiungiamo la meta description recuperata all'inizio
    final_text = f"{text} {meta_desc}"

    # 6. PULIZIA FINALE ENTITIES E SPAZI
    # BeautifulSoup gestisce le entità (&amp;) automaticamente in get_text(), 
    # ma rimuoviamo spazi multipli
    final_text = re.sub(r'\s+', ' ', final_text).strip()

    return final_text

In [15]:
test_string = """
<div>
    <p>Chief&#39;s decision: &quot;No&quot;.</p>
    <p>Price: 50&euro;</p>
</div>
"""

# Chiamiamo la tua funzione
clean_output = clean_html_professional(test_string)

print(f"Originale sporco: {test_string}")
print("-" * 20)
print(f"Pulito: {clean_output}")

Originale sporco: 
<div>
    <p>Chief&#39;s decision: &quot;No&quot;.</p>
    <p>Price: 50&euro;</p>
</div>

--------------------
Pulito: Chief's decision: "No". Price: 50€
